#!/usr/bin/env bash
# Last-touched: 2026-08-05 — senior review: restructured to the Google Shell Style Guide
# (main function, readonly constants, errors to STDERR). Behaviour unchanged.
#
# Generates .env with STRONG RANDOM secrets (nothing hardcoded), wires the chosen
# edition, and brings the stack up. Re-run with --force to regenerate .env.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_DIR
readonly ENV_FILE="${REPO_DIR}/.env"

# Image coordinates verified 2026-08-05 against each registry. Change deliberately, and
# re-pin the digest when you do: a tag can be moved by whoever can push, a digest cannot.
# Every image here is pinned — no `latest`, no empty digest.
readonly STALWART_VERSION_DEFAULT="v0.11.8"
readonly STALWART_DIGEST_DEFAULT="@sha256:a5ce0615640b29a01c0a55b9fff6dd2c9dfa261ec87862c22e4db7e0254cdb1f"
readonly BULWARK_IMAGE_DEFAULT="ghcr.io/bulwarkmail/webmail"
# Patch floor is 1.4.11: anything below it carries CVE-2026-34834 (auth bypass) and
# CVE-2026-34833 (password disclosure). See SECURITY.md before changing this.
readonly BULWARK_VERSION_DEFAULT="v1.7.8"
readonly BULWARK_DIGEST_DEFAULT="@sha256:1ea45e292e7baf84eccdfe3d7ed96fe4487f2b95025a6ab569706915f6798979"
readonly NGINX_VERSION_DEFAULT="1.30.4-alpine"
readonly NGINX_DIGEST_DEFAULT="@sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46"
readonly KEYCLOAK_VERSION_DEFAULT="26.7.0"
readonly KEYCLOAK_DIGEST_DEFAULT="@sha256:0f198be292568439d700cdbfb893e69a6009bb43a94a06a945b1d3d506c76b13"
readonly POSTGRES_VERSION_DEFAULT="17-alpine"
readonly POSTGRES_DIGEST_DEFAULT="@sha256:778d0b486d6daa02b77434d0358ec57a1b21fd8b6d22ac2eef56a33e816928f6"

# Errors go to STDERR so that redirecting stdout to a log never swallows them.
err() { printf '%s\n' "$*" >&2; }

# Write a config from its template, but never silently destroy an operator's edits.
# A re-run with --force must still refresh the domain, so the old file is kept beside it
# rather than preserved in place (which would leave a stale domain in the config).
install_config() {
  local src="$1" dst="$2" backup
  if [[ -f "${dst}" ]]; then
    backup="${dst}.bak.$(date +%Y%m%d%H%M%S)"
    cp -p "${dst}" "${backup}"
    echo "ℹ️  Existing $(basename "${dst}") saved as $(basename "${backup}")"
  fi
  cp -f "${src}" "${dst}"
}

gen() { openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-40; }

# A hostname is interpolated into sed and into nginx config — validate it.
valid_domain() { [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]; }

main() {
  local force="${1:-}"
  local edition mail_domain app_name idp_domain
  local tls_fullchain tls_privkey admin_secret go
  local compose_args

  if [[ -f "${ENV_FILE}" && "${force}" != "--force" ]]; then
    err "✋ .env already exists. Re-run with --force to regenerate (rotates secrets)."
    exit 1
  fi
  command -v docker >/dev/null || { err "❌ docker not found"; exit 1; }
  command -v openssl >/dev/null || { err "❌ openssl not found"; exit 1; }

  # Secrets must never exist as world-readable, not even for the moment before chmod.
  umask 077

  echo "Which edition?"
  echo "  1) Full Mail       — mail server + webmail (native login). Simple, no identity server. [default]"
  echo "  2) Mail + SSO      — adds Keycloak (OIDC/SSO). For centralized identity."
  read -rp "Choose [1/2]: " edition
  edition="${edition:-1}"
  [[ "${edition}" == "1" || "${edition}" == "2" ]] || { err "❌ choose 1 or 2"; exit 1; }

  read -rp "Mail domain (e.g. mail.example.com): " mail_domain
  valid_domain "${mail_domain}" || { err "❌ '${mail_domain}' is not a valid domain name"; exit 1; }
  read -rp "Display name for the webmail app [Mail]: " app_name
  app_name="${app_name:-Mail}"

  idp_domain=""
  if [[ "${edition}" == "2" ]]; then
    read -rp "SSO/IdP domain (e.g. id.example.com): " idp_domain
    valid_domain "${idp_domain}" || { err "❌ '${idp_domain}' is not a valid domain name"; exit 1; }
  fi

  # Let's Encrypt `live/` entries are symlinks into `archive/`. Docker bind-mounts the
  # symlink itself, so the target must be resolved on the host or the file dangles.
  tls_fullchain="/etc/letsencrypt/live/${mail_domain}/fullchain.pem"
  tls_privkey="/etc/letsencrypt/live/${mail_domain}/privkey.pem"
  [[ -e "${tls_fullchain}" ]] && tls_fullchain="$(readlink -f "${tls_fullchain}")"
  [[ -e "${tls_privkey}" ]] && tls_privkey="$(readlink -f "${tls_privkey}")"
  if [[ ! -e "${tls_fullchain}" || ! -e "${tls_privkey}" ]]; then
    err "⚠️  TLS cert not found for ${mail_domain}."
    err "    Issue one first (e.g. certbot certonly --standalone -d ${mail_domain}),"
    err "    then re-run. Paths written to .env: ${tls_fullchain} / ${tls_privkey}"
  fi

  echo "🔐 Generating strong secrets…"
  admin_secret="$(gen)"
  {
    echo "# Generated by install.sh on $(hostname) — DO NOT COMMIT."
    echo "MAIL_DOMAIN=${mail_domain}"
    echo "APP_NAME=${app_name}"
    echo "STALWART_VERSION=${STALWART_VERSION_DEFAULT}"
    echo "STALWART_DIGEST=${STALWART_DIGEST_DEFAULT}"
    echo "BULWARK_IMAGE=${BULWARK_IMAGE_DEFAULT}"
    echo "BULWARK_VERSION=${BULWARK_VERSION_DEFAULT}"
    echo "BULWARK_DIGEST=${BULWARK_DIGEST_DEFAULT}"
    echo "NGINX_VERSION=${NGINX_VERSION_DEFAULT}"
    echo "NGINX_DIGEST=${NGINX_DIGEST_DEFAULT}"
    echo "TLS_FULLCHAIN=${tls_fullchain}"
    echo "TLS_PRIVKEY=${tls_privkey}"
    echo "WEBMAIL_SESSION_SECRET=$(gen)"
    echo "STALWART_FALLBACK_ADMIN_SECRET=${admin_secret}"
    if [[ "${edition}" == "2" ]]; then
      echo "IDP_DOMAIN=${idp_domain}"
      echo "KEYCLOAK_VERSION=${KEYCLOAK_VERSION_DEFAULT}"
      # Full URL is the Keycloak 25+ form; drop the scheme if you pin an older Keycloak.
      echo "KC_HOSTNAME_VALUE=https://${idp_domain}"
      echo "OAUTH_CLIENT_ID=webmail"
      echo "OAUTH_CLIENT_SECRET=$(gen)"
      echo "OAUTH_ISSUER_URL=https://${idp_domain}/realms/mail"
      echo "KEYCLOAK_ADMIN_USER=admin"
      echo "KEYCLOAK_ADMIN_PASSWORD=$(gen)"
      echo "KEYCLOAK_DIGEST=${KEYCLOAK_DIGEST_DEFAULT}"
      echo "POSTGRES_VERSION=${POSTGRES_VERSION_DEFAULT}"
      echo "POSTGRES_DIGEST=${POSTGRES_DIGEST_DEFAULT}"
      echo "KC_DB_NAME=keycloak"
      echo "KC_DB_USERNAME=keycloak"
      echo "KC_DB_PASSWORD=$(gen)"
    fi
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "✅ Wrote ${ENV_FILE} (mode 600)."

  # Materialise config from templates.
  cp -n "${REPO_DIR}/config/stalwart/config.toml.example" \
        "${REPO_DIR}/config/stalwart/config.toml"
  if [[ "${edition}" == "2" ]]; then
    install_config "${REPO_DIR}/config/nginx/mail.sso.conf.example" \
                   "${REPO_DIR}/config/nginx/mail.sso.conf"
    sed -i "s/MAIL_DOMAIN_PLACEHOLDER/${mail_domain}/g" "${REPO_DIR}/config/nginx/mail.sso.conf"
    compose_args=(-f docker-compose.yml -f docker-compose.sso.yml)
    echo
    echo "ℹ️  SSO edition: a PostgreSQL service (\`db\`) is included and starts automatically."
    echo "    Keycloak waits for it to pass its healthcheck before booting."
  else
    install_config "${REPO_DIR}/config/nginx/mail.conf.example" \
                   "${REPO_DIR}/config/nginx/mail.conf"
    sed -i "s/MAIL_DOMAIN_PLACEHOLDER/${mail_domain}/g" "${REPO_DIR}/config/nginx/mail.conf"
    compose_args=(-f docker-compose.yml)
  fi

  echo
  read -rp "Start now with 'docker compose ${compose_args[*]} up -d'? [y/N]: " go
  if [[ "${go,,}" == "y" ]]; then
    docker compose --env-file "${ENV_FILE}" "${compose_args[@]}" up -d
    print_next_steps "${mail_domain}"
  else
    echo "Skipped. Run: docker compose ${compose_args[*]} up -d"
  fi
}

# The admin API is the only way in on a fresh install, and the roles field is the step
# everybody misses — see SUPPORT.md "Common problems".
print_next_steps() {
  local mail_domain="$1"
  local domain="${mail_domain#*.}"
  cat <<EOF

🚀 Up. Next:
  1. Create your domain and first mailbox against the admin API:
       curl -u admin:\$STALWART_FALLBACK_ADMIN_SECRET -X POST http://127.0.0.1:8080/api/principal \\
         -H 'Content-Type: application/json' -d '{"type":"domain","name":"${domain}"}'
       curl -u admin:\$STALWART_FALLBACK_ADMIN_SECRET -X POST http://127.0.0.1:8080/api/principal \\
         -H 'Content-Type: application/json' \\
         -d '{"type":"individual","name":"you@${domain}","secrets":["<password>"],"emails":["you@${domain}"],"roles":["user"]}'
     (the "roles":["user"] part is required — without it SMTP AUTH returns 550 5.7.1)
  2. Set your DNS records — see docs/DNS.md.
  3. Read SECURITY.md before exposing this to the internet.
EOF
}

main "$@"
